spring:
  application:
    name: rutina-gym-api
  
  datasource:
    url: jdbc:h2:mem:rutina_gym_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Configuración de Prolog
prolog:
  path: prolog
  timeout: 30
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.rutinagym: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
